# Generated by Django 5.2.12 on 2026-05-04 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20260504_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillhole',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='company_report',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='current_epm',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='date_commenced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='drill_company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='drill_type',
            field=models.CharField(blank=True, choices=[('RC', 'Reverse Circulation'), ('DDH', 'Diamond Drill Hole'), ('RAB', 'Rotary Air Blast'), ('AC', 'Air Core')], max_length=8),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='elevation',
            field=models.FloatField(blank=True, help_text='Collar elevation (RL) in metres', null=True),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='hole_id_original',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='original_epm',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='source_crs',
            field=models.CharField(blank=True, help_text='e.g. EPSG:28356', max_length=32),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='source_easting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='source_northing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='year_report',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drillhole',
            name='azimuth',
            field=models.FloatField(blank=True, help_text='Bearing true north (0-360 degrees)', null=True),
        ),
        migrations.CreateModel(
            name='AssayResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('from_depth', models.FloatField()),
                ('to_depth', models.FloatField()),
                ('lab_batch_number', models.CharField(blank=True, max_length=64)),
                ('sample_number', models.CharField(blank=True, max_length=64)),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('au_ppm', models.FloatField(blank=True, null=True)),
                ('au_ppm_check1', models.FloatField(blank=True, null=True)),
                ('au_ppm_check2', models.FloatField(blank=True, null=True)),
                ('cu_ppm', models.FloatField(blank=True, null=True)),
                ('pb_ppm', models.FloatField(blank=True, null=True)),
                ('zn_ppm', models.FloatField(blank=True, null=True)),
                ('ag_ppm', models.FloatField(blank=True, null=True)),
                ('as_ppm', models.FloatField(blank=True, null=True)),
                ('bi_ppm', models.FloatField(blank=True, null=True)),
                ('cd_ppm', models.FloatField(blank=True, null=True)),
                ('sb_ppm', models.FloatField(blank=True, null=True)),
                ('mn_ppm', models.FloatField(blank=True, null=True)),
                ('mo_ppm', models.FloatField(blank=True, null=True)),
                ('pt_ppb', models.FloatField(blank=True, null=True)),
                ('pd_ppb', models.FloatField(blank=True, null=True)),
                ('laboratory', models.CharField(blank=True, max_length=64)),
                ('au_method', models.CharField(blank=True, max_length=32)),
                ('cu_method', models.CharField(blank=True, max_length=32)),
                ('cu_method_2', models.CharField(blank=True, max_length=32)),
                ('pb_method', models.CharField(blank=True, max_length=32)),
                ('zn_method', models.CharField(blank=True, max_length=32)),
                ('ag_method', models.CharField(blank=True, max_length=32)),
                ('as_method', models.CharField(blank=True, max_length=32)),
                ('bi_method', models.CharField(blank=True, max_length=32)),
                ('cd_method', models.CharField(blank=True, max_length=32)),
                ('sb_method', models.CharField(blank=True, max_length=32)),
                ('mn_method', models.CharField(blank=True, max_length=32)),
                ('mo_method', models.CharField(blank=True, max_length=32)),
                ('pt_method', models.CharField(blank=True, max_length=32)),
                ('pd_method', models.CharField(blank=True, max_length=32)),
                ('drillhole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assays', to='core.drillhole')),
            ],
            options={
                'ordering': ['drillhole', 'from_depth'],
            },
        ),
        migrations.CreateModel(
            name='DrillholeSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('depth', models.FloatField(help_text='Metres down hole')),
                ('dip', models.FloatField(blank=True, help_text='Dip angle in degrees', null=True)),
                ('azimuth_tn', models.FloatField(blank=True, help_text='Azimuth true north (0-360)', null=True)),
                ('azimuth_mag', models.FloatField(blank=True, help_text='Azimuth magnetic (0-360)', null=True)),
                ('comment', models.CharField(blank=True, max_length=128)),
                ('drillhole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core.drillhole')),
            ],
            options={
                'ordering': ['drillhole', 'depth'],
            },
        ),
        migrations.CreateModel(
            name='LithologyInterval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('from_depth', models.FloatField()),
                ('to_depth', models.FloatField()),
                ('lithology', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('mineralisation', models.CharField(blank=True, max_length=128)),
                ('hardness', models.CharField(blank=True, max_length=64)),
                ('weathering', models.CharField(blank=True, max_length=64)),
                ('acid_reaction', models.CharField(blank=True, max_length=64)),
                ('colour', models.CharField(blank=True, max_length=64)),
                ('oxidation', models.CharField(blank=True, max_length=64)),
                ('mineralisation_b', models.CharField(blank=True, help_text='Second mineralisation column from source (col L)', max_length=128)),
                ('mineralisation_2', models.CharField(blank=True, max_length=128)),
                ('alteration', models.CharField(blank=True, max_length=128)),
                ('alteration_2', models.CharField(blank=True, max_length=128)),
                ('veins', models.CharField(blank=True, max_length=128)),
                ('recovery_pct', models.CharField(blank=True, max_length=32)),
                ('core_size', models.CharField(blank=True, max_length=32)),
                ('drillhole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lithology', to='core.drillhole')),
            ],
            options={
                'ordering': ['drillhole', 'from_depth'],
            },
        ),
    ]
