# Generated by Django 5.2.12 on 2026-05-09 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_drillhole_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.prospect'),
        ),
    ]
