# Generated by Django 5.2.12 on 2026-05-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_savedreport_prospect_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=16),
        ),
    ]
